spring.application.name=Metro_ticket_backend
spring.datasource.url=jdbc:postgresql://dpg-d6r79pfdiees73c3e3jg-a:5432/metro_db_esl9
spring.datasource.username=root
spring.datasource.password=y8LeYigJ3I4MC1EJwqXHpESkGI9Dy9Nt

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=bXlTdXBlclNlY3JldEtleTEyMzQ1Njc4OTAxMjM0NTY=
server.port=${PORT:8080}

